apiVersion: v2
description: An automated observability platform for cloud-native developers.
name: deepflow-agent
engine: gotpl
type: application
version: 0.1.008
appVersion: "6.1.1"
kubeVersion: ">=1.16.0-0"
sources:
  - https://github.com/deepflowys/deepflow
home: https://github.com/deepflowys/deepflow
keywords:
  - deepflow
icon: https://raw.githubusercontent.com/deepflowys/deepflow-charts/main/deepflow.png